const DungeonDB = [
  {
    name: "Millstone Mines",
    cost: 300,
    loot: [
      { name: "Improved Fishing Rod", rarity: "Refined" },
      { name: "Improved Pickaxe", rarity: "Refined" },
      { name: "Improved Felling Axe", rarity: "Refined" },
      { name: "Alchemy Chest", rarity: "Refined" },
    ],
  },
  {
    name: "Vineyard Labyrinth",
    cost: 1200,
    loot: [
      { name: "Rivertamer", rarity: "Refined" },
      { name: "Veinseeker", rarity: "Refined" },
      { name: "Timberfall Talon", rarity: "Refined" },
      { name: "Alchemy Chest", rarity: "Refined" },
    ],
  },
  {
    name: "Verdant Veil",
    cost: 2400,
    loot: [
      { name: "Seasongs Lure", rarity: "Refined" },
      { name: "Ironbite", rarity: "Refined" },
      { name: "Wildwood Chopper", rarity: "Refined" },
      { name: "Alchemy Chest", rarity: "Premium" },
    ],
  },
  {
    name: "Sylvan Sanctum",
    cost: 3600,
    loot: [
      { name: "Moonshimmer", rarity: "Premium" },
      { name: "Boulder Breaker", rarity: "Premium" },
      { name: "Leafblade", rarity: "Premium" },
      { name: "Alchemy Chest", rarity: "Epic" },
    ],
  },
  {
    name: "Whispering Catacombs",
    cost: 4800,
    loot: [
      { name: "Shadowbane", rarity: "Legendary" },
      { name: "Soulrender", rarity: "Legendary" },
      { name: "Shadowstrike", rarity: "Legendary" },
      { name: "Venomfang", rarity: "Legendary" },
      { name: "Whisperwind", rarity: "Legendary" },
      { name: "Stormcaster", rarity: "Legendary" },
      { name: "Radiant Crest", rarity: "Legendary" },
      { name: "Shadow Helm", rarity: "Legendary" },
      { name: "Ironclad Gauntlets", rarity: "Legendary" },
      { name: "Stormguard Plate", rarity: "Legendary" },
      { name: "Dragonheart Plate", rarity: "Legendary" },
      { name: "Stormstrider Greaves", rarity: "Legendary" },
      { name: "Shadowstep Greaves", rarity: "Legendary" },
      { name: "Swiftwind Boots", rarity: "Legendary" },
      { name: "Aegis of the Seraph", rarity: "Legendary" },
      { name: "Stormguard Shield", rarity: "Legendary" },
      { name: "Alchemy Chest", rarity: "Epic" },
    ],
  },
  {
    name: "Cursed Asylum",
    cost: 6000,
    loot: [
      { name: "Frostbite", rarity: "Legendary" },
      { name: "Stormbringer", rarity: "Legendary" },
      { name: "Bloodletter", rarity: "Legendary" },
      { name: "Whisperblade", rarity: "Legendary" },
      { name: "Shadow Shot", rarity: "Legendary" },
      { name: "Frostbite Shot", rarity: "Legendary" },
      { name: "Frostguard Visage", rarity: "Legendary" },
      { name: "Sentinels Gaze", rarity: "Legendary" },
      { name: "Dragonfire Grasp", rarity: "Legendary" },
      { name: "Shadowstrike Grips", rarity: "Legendary" },
      { name: "Frostbite Gauntlets", rarity: "Legendary" },
      { name: "Shadowcloak Vestments", rarity: "Legendary" },
      { name: "Frostbite Plate", rarity: "Legendary" },
      { name: "Frostbite Legguards", rarity: "Legendary" },
      { name: "Sentinel's Resolve", rarity: "Legendary" },
      { name: "Shadowstep Footwear", rarity: "Legendary" },
      { name: "Soulward Barrier", rarity: "Legendary" },
      { name: "Hydra's Coil", rarity: "Premium" },
      { name: "Earthshaker", rarity: "Premium" },
      { name: "Grove Cleaver", rarity: "Premium" },
      { name: "Alchemy Chest", rarity: "Epic" },
    ],
  },
  {
    name: "Forgotten Archives",
    cost: 9000,
    loot: [
      { name: "Doomblade", rarity: "Legendary" },
      { name: "Serpentstrike", rarity: "Legendary" },
      { name: "Serpent's Kiss", rarity: "Legendary" },
      { name: "Moonshadow", rarity: "Legendary" },
      { name: "Serpent's Arrow", rarity: "Legendary" },
      { name: "Viper", rarity: "Legendary" },
      { name: "Celestial Crown", rarity: "Legendary" },
      { name: "Emberfire Helm", rarity: "Legendary" },
      { name: "Titan's Embrace", rarity: "Legendary" },
      { name: "Celestial Touch Gloves", rarity: "Legendary" },
      { name: "Sentinel's Embrace", rarity: "Legendary" },
      { name: "Celestial Striders", rarity: "Legendary" },
      { name: "Frostbite Walkers", rarity: "Legendary" },
      { name: "Guardian's Stride", rarity: "Legendary" },
      { name: "Flamebreaker Buckler", rarity: "Legendary" },
      { name: "Shadowbound Ward", rarity: "Legendary" },
      { name: "Alchemy Chest", rarity: "Legendary" },
    ],
  },
  {
    name: "Crystal Forge",
    cost: 15000,
    loot: [
      { name: "Celestial Edge", rarity: "Legendary" },
      { name: "Bloodmoon Sword", rarity: "Legendary" },
      { name: "Quickstrike", rarity: "Legendary" },
      { name: "Runeblade Dagger", rarity: "Legendary" },
      { name: "Moonshot", rarity: "Legendary" },
      { name: "Stormsong", rarity: "Legendary" },
      { name: "Thunder Helm", rarity: "Legendary" },
      { name: "Emberfist", rarity: "Legendary" },
      { name: "Celestial Radiance", rarity: "Legendary" },
      { name: "Ironbark Cuirass", rarity: "Legendary" },
      { name: "Emberfoot Greaves", rarity: "Legendary" },
      { name: "Thunderclash Greaves", rarity: "Legendary" },
      { name: "Celestial Ascenders", rarity: "Legendary" },
      { name: "Emberfoot Boots", rarity: "Legendary" },
      { name: "Frostbite Guard", rarity: "Legendary" },
      { name: "Sentinel's Bulwark", rarity: "Legendary" },
      { name: "Ocean's Whisper", rarity: "Epic" },
      { name: "Stone Splinter", rarity: "Epic" },
      { name: "Branchbane Hatchet", rarity: "Epic" },
      { name: "Alchemy Chest", rarity: "Legendary" },
    ],
  },
  {
    name: "Frostbite Spire",
    cost: 18000,
    loot: [
      { name: "Whisperwind Sword", rarity: "Legendary" },
      { name: "Voidslayer", rarity: "Legendary" },
      { name: "Shadowfang", rarity: "Legendary" },
      { name: "Emberheart", rarity: "Legendary" },
      { name: "Otto's Mask", rarity: "Legendary" },
      { name: "Shadowbane Visor", rarity: "Legendary" },
      { name: "Thunderclap", rarity: "Legendary" },
      { name: "Soulgrasp", rarity: "Legendary" },
      { name: "Flameguard Plate", rarity: "Legendary" },
      { name: "Stormbreaker Mail", rarity: "Legendary" },
      { name: "Soulforge Legplates", rarity: "Legendary" },
      { name: "Shadowbane Greaves", rarity: "Legendary" },
      { name: "Thunderstrike Steps", rarity: "Legendary" },
      { name: "Soulwalkers", rarity: "Legendary" },
      { name: "Celestial Aegis", rarity: "Legendary" },
      { name: "Thunderstrike Barrier", rarity: "Legendary" },
      { name: "Alchemy Chest", rarity: "Legendary" },
    ],
  },
  {
    name: "Zenith's Sanctum",
    cost: 21000,
    loot: [
      { name: "Sunfire", rarity: "Legendary" },
      { name: "Flamebrand", rarity: "Legendary" },
      { name: "Soulshard", rarity: "Legendary" },
      { name: "Piercer", rarity: "Legendary" },
      { name: "Sunseeker", rarity: "Legendary" },
      { name: "Windborne Casque", rarity: "Legendary" },
      { name: "Stormbreaker Helm", rarity: "Legendary" },
      { name: "Shadowstep Gauntlets", rarity: "Legendary" },
      { name: "Sentinel's Gauntlets", rarity: "Legendary" },
      { name: "Shadoweave Raiment", rarity: "Legendary" },
      { name: "Crystalheart Plate", rarity: "Legendary" },
      { name: "Windrider Greaves", rarity: "Legendary" },
      { name: "Stomerbreaker Treads", rarity: "Legendary" },
      { name: "Shadowbane Footguards", rarity: "Legendary" },
      { name: "Windrider Striders", rarity: "Legendary" },
      { name: "Essenceweave Shield", rarity: "Legendary" },
      { name: "Alchemy Chest", rarity: "Legendary" },
    ],
  },
  {
    name: "Mirage Citadel",
    cost: 24000,
    loot: [
      { name: "Thunderstrike", rarity: "Legendary" },
      { name: "Nightfall Sword", rarity: "Legendary" },
      { name: "Night's Whisper", rarity: "Legendary" },
      { name: "Eclipse", rarity: "Legendary" },
      { name: "Thundershot", rarity: "Legendary" },
      { name: "Nightshade Bow", rarity: "Legendary" },
      { name: "Voidwalker Cowl", rarity: "Legendary" },
      { name: "Lunar Radiance", rarity: "Legendary" },
      { name: "Flameguard Gauntlers", rarity: "Legendary" },
      { name: "Stomerbreaker Gauntlets", rarity: "Legendary" },
      { name: "Serpent Scale", rarity: "Legendary" },
      { name: "Phoenix Soulplate", rarity: "Legendary" },
      { name: "Voidwalker Striders", rarity: "Legendary" },
      { name: "Stormbreaker Boots", rarity: "Legendary" },
      { name: "Moonshadow Guard", rarity: "Legendary" },
      { name: "Ashenfire Ward", rarity: "Legendary" },
      { name: "Alchemy Chest", rarity: "Mythic" },
    ],
  },
  {
    name: "Eden's Embrace",
    cost: 27000,
    loot: [
      { name: "Dawnbreaker Sword", rarity: "Legendary" },
      { name: "Runeblade Sword", rarity: "Mythic" },
      { name: "Duskblade", rarity: "Legendary" },
      { name: "Silent Reaper", rarity: "Mythic" },
      { name: "Dawnbreaker Bow", rarity: "Legendary" },
      { name: "Silverthorn Bow", rarity: "Mythic" },
      { name: "Ashenfire Crown", rarity: "Legendary" },
      { name: "Nightshade Mask", rarity: "Mythic" },
      { name: "Voidrend Gauntlets", rarity: "Legendary" },
      { name: "Windrider", rarity: "Mythic" },
      { name: "Echosteel Breastplate", rarity: "Mythic" },
      { name: "Lunarweave Leggings", rarity: "Legendary" },
      { name: "Nightshade Greaves", rarity: "Mythic" },
      { name: "Voidstep Boots", rarity: "Legendary" },
      { name: "Nightshade Boots", rarity: "Mythic" },
      { name: "Runebound Bulwark", rarity: "Legendary" },
      { name: "Shadewalker Bulwark", rarity: "Mythic" },
      { name: "Rune-etched Reeler", rarity: "Epic" },
      { name: "Corestrike", rarity: "Epic" },
      { name: "Silvan Splitter", rarity: "Epic" },
      { name: "Alchemy Chest", rarity: "Mythic" },
    ],
  },
  {
    name: "Arboreal Labyrinth",
    cost: 30000,
    loot: [
      { name: "Starshard", rarity: "Legendary" },
      { name: "Phoenix Requiem", rarity: "Mythic" },
      { name: "Ghostwalker", rarity: "Legendary" },
      { name: "Silvermist", rarity: "Mythic" },
      { name: "Starshower", rarity: "Legendary" },
      { name: "Bloodmoon Bow", rarity: "Mythic" },
      { name: "Verdant Guardian Helm", rarity: "Legendary" },
      { name: "Glimmersteel Helm", rarity: "Mythic" },
      { name: "Lunarweave Gloves", rarity: "Legendary" },
      { name: "Bloodforged Gauntlets", rarity: "Legendary" },
      { name: "Grasps of Pretection", rarity: "Mythic" },
      { name: "Guardian's Valor", rarity: "Legendary" },
      { name: "Verdant Chainmail", rarity: "Mythic" },
      { name: "Runebound Shinplates", rarity: "Legendary" },
      { name: "Glimmersteel Pathguards", rarity: "Mythic" },
      { name: "Ashenfire Boots", rarity: "Legendary" },
      { name: "Glimmersteel Boots", rarity: "Mythic" },
      { name: "Bloodbane Barrier", rarity: "Legendary" },
      { name: "Stormbringer Buckler", rarity: "Mythic" },
      { name: "Alchemy Chest", rarity: "Mythic" },
    ],
  },
  {
    name: "Bloodmoon Manor",
    cost: 33000,
    loot: [
      { name: "Grimslayer", rarity: "Legendary" },
      { name: "Death's Embrace", rarity: "Mythic" },
      { name: "Nightfall Dagger", rarity: "Mythic" },
      { name: "Fury", rarity: "Legendary" },
      { name: "Death's Touch", rarity: "Mythic" },
      { name: "Bloodforged Helm", rarity: "Legendary" },
      { name: "Soul", rarity: "Mythic" },
      { name: "Phoenixclaw Gauntlets", rarity: "Legendary" },
      { name: "Gloves of the Protector", rarity: "Mythic" },
      { name: "Dreadbane Armor", rarity: "Legendary" },
      { name: "Ashenplate Cuirass", rarity: "Mythic" },
      { name: "Phoenix Greaves", rarity: "Legendary" },
      { name: "Soulshield Legplates", rarity: "Mythic" },
      { name: "Verdant Boots", rarity: "Legendary" },
      { name: "Soulshield Treads", rarity: "Mythic" },
      { name: "Phoenixguard Shield", rarity: "Legendary" },
      { name: "Ironbark Protector", rarity: "Mythic" },
      { name: "Arboreal Ender", rarity: "Legendary" },
      { name: "Alchemy Chest", rarity: "Mythic" },
    ],
  },
  {
    name: "Ruins of Old Ranhor",
    cost: 36000,
    loot: [
      { name: "Silverthorn Sword", rarity: "Mythic" },
      { name: "Starglitter", rarity: "Legendary" },
      { name: "Widow's Kiss", rarity: "Mythic" },
      { name: "Grimwood", rarity: "Legendary" },
      { name: "Soulstring", rarity: "Mythic" },
      { name: "Phoenix Crown", rarity: "Legendary" },
      { name: "Whispersong", rarity: "Mythic" },
      { name: "Nightshade Grips", rarity: "Legendary" },
      { name: "Sacred Grasp", rarity: "Mythic" },
      { name: "Soulguard Armor", rarity: "Mythic" },
      { name: "Whisperstep Greaves", rarity: "Mythic" },
      { name: "Whisperwind Boots", rarity: "Mythic" },
      { name: "Soulshield of Redemption", rarity: "Mythic" },
      { name: "Kraken's Grasp", rarity: "Legendary" },
      { name: "Alchemy Chest", rarity: "Mythic" },
    ],
  },
  {
    name: "Volcanic Depths",
    cost: 39000,
    loot: [
      { name: "Emberfang", rarity: "Legendary" },
      { name: "Bloodthirst", rarity: "Mythic" },
      { name: "Bloodthorn", rarity: "Legendary" },
      { name: "Fatebreaker", rarity: "Mythic" },
      { name: "Ashenwind", rarity: "Legendary" },
      { name: "Archdemon", rarity: "Mythic" },
      { name: "Runebound Helm", rarity: "Legendary" },
      { name: "Balthazar's Head", rarity: "Mythic" },
      { name: "Warfists", rarity: "Mythic" },
      { name: "Bloodforged Harness", rarity: "Legendary" },
      { name: "Windrider Harness", rarity: "Mythic" },
      { name: "Ashenfire Greaves", rarity: "Legendary" },
      { name: "Twilight Veilguards", rarity: "Mythic" },
      { name: "Lunarweave Boots", rarity: "Legendary" },
      { name: "Twilight Veilwalkers", rarity: "Mythic" },
      { name: "Verdant Sentinel", rarity: "Legendary" },
      { name: "Deathgate", rarity: "Mythic" },
      { name: "Boulder's Bane", rarity: "Legendary" },
      { name: "Alchemy Chest", rarity: "Mythic" },
    ],
  },
  {
    name: "Celestial Enclave",
    cost: 42000,
    loot: [
      { name: "Tempest's Fury", rarity: "Legendary" },
      { name: "Everflame", rarity: "Mythic" },
      { name: "Emberstrike", rarity: "Legendary" },
      { name: "Dreadspike", rarity: "Mythic" },
      { name: "Sting", rarity: "Mythic" },
      { name: "Thunder", rarity: "Mythic" },
      { name: "Nature's Grasp", rarity: "Mythic" },
      { name: "Starfire Plate", rarity: "Legendary" },
      { name: "Twilight", rarity: "Mythic" },
      { name: "Verdant Greaves", rarity: "Legendary" },
      { name: "Stormbringer Greaves", rarity: "Mythic" },
      { name: "Runebound Footwraps", rarity: "Legendary" },
      { name: "Stormbringer Striders", rarity: "Mythic" },
      { name: "Twilight Sanctum", rarity: "Legendary" },
      { name: "Brute", rarity: "Mythic" },
      { name: "Aqua Reaper", rarity: "Mythic" },
      { name: "Alchemy Chest", rarity: "Mythic" },
    ],
  },
  {
    name: "The Nexus",
    cost: 45000,
    loot: [
      { name: "Excalibur", rarity: "Mythic" },
      { name: "Moonlance", rarity: "Mythic" },
      { name: "Divinity", rarity: "Mythic" },
      { name: "Fortune", rarity: "Mythic" },
      { name: "Fists of Fury", rarity: "Mythic" },
      { name: "Moonshadow Vestment", rarity: "Legendary" },
      { name: "Corruption", rarity: "Mythic" },
      { name: "Bloodforged Legguards", rarity: "Legendary" },
      { name: "Dirella's Protection", rarity: "Mythic" },
      { name: "Bloodforged Boots", rarity: "Legendary" },
      { name: "Phoenix Boots", rarity: "Legendary" },
      { name: "Fatebreaker Footguards", rarity: "Mythic" },
      { name: "Glimmersteel Ward", rarity: "Legendary" },
      { name: "Colossus", rarity: "Mythic" },
      { name: "Earth Destroyer", rarity: "Mythic" },
      { name: "Forest Reaver", rarity: "Mythic" },
      { name: "Alchemy Chest", rarity: "Mythic" },
    ],
  },
];

export default DungeonDB;
